sonar.projectKey=HassanAhmed270_cohort-9-mern-7723-hassan
sonar.organization=hassanahmed270

sonar.projectName=cohort-9-mern-7723-hassan
sonar.projectVersion=1.0

sonar.sources=backend,frontend

sonar.tests=backend/tests,frontend/src

sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.coverage.exclusions=backend/config/**,backend/index.js,backend/tests/**,frontend/src/config.js,frontend/src/main.jsx,frontend/babel.config.cjs,frontend/jest.config.cjs

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8