name: Build
on:
  push:
    branches:
      - main
      - sonarCheck
      - ProfilePageAndAdditionalFeatures
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd5f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend deps
        run: npm install
        working-directory: backend

      - name: Run backend tests with coverage
        run: npm run test:coverage
        working-directory: backend
        continue-on-error: true

      - name: Install frontend deps
        run: npm install
        working-directory: frontend

      - name: Run frontend tests with coverage
        run: npm test -- --coverage
        working-directory: frontend
        continue-on-error: true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}